[package]
name = "axum_tries"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
hyper = { version = "0.14.27", features = ["full"] }
tokio = { version = "1.33.0", features = ["full"] }
tower = "0.4.13"
serde_json = "1.0"
dotenv = "0.15.0"
futures = "0.3"
mongodb = "2.7.1"
serde = "1.0.192"
axum-macros = "0.3.8"
once_cell = "1.18.0"
async-once-cell = "0.5.3"
bcrypt = "0.15.0"
chrono = "0.4.31"
jsonwebtoken = "9.2.0"
